/* 🤖 this file was generated by svg-to-ts*/
export default {
  bin:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 3V1.5A1.5 1.5 0 009.5 0h-4A1.5 1.5 0 004 1.5V3H0v1h1v9.5A1.5 1.5 0 002.5 15h10a1.5 1.5 0 001.5-1.5V4h1V3h-4zM5 1.5a.5.5 0 01.5-.5h4a.5.5 0 01.5.5V3H5V1.5zM7 7v5h1V7H7zm-3 5V9h1v3H4zm6-3v3h1V9h-1z"/></svg>',
  cancel:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15"><path d="M1.5 1.5l12 12m-12 0l12-12" stroke="currentColor"/></svg>',
  edit:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15"><path d="M9.854.146a.5.5 0 00-.708 0L6.5 2.793 12.207 8.5l2.647-2.646a.5.5 0 000-.708l-5-5zM0 9.293L5.793 3.5 11.5 9.207 5.707 15H.5a.5.5 0 01-.5-.5V9.293zM8 15h7v-1H8v1z"/></svg>',
  tag:
    '<svg version="1.2" viewBox="0 0 529 529" preserveAspectRatio="xMidYMid" fill-rule="evenodd" stroke-width="28.222" stroke-linejoin="round" xmlns="http://www.w3.org/2000/svg"><defs class="ClipPathGroup"><clipPath id="a" clipPathUnits="userSpaceOnUse"><path d="M0 0h529v529H0z"/></clipPath></defs><g class="SlideGroup"><g class="Slide" clip-path="url(#a)"><g class="Page"><g class="Graphic"><path class="BoundingBox" d="M0 0h529v529H0z"/><defs><clipPath id="b" clipPathUnits="userSpaceOnUse"><path d="M0 0h528v528H0V0z"/></clipPath></defs><g clip-path="url(#b)"><path d="M2 255c-1 3-2 6-2 9s1 6 2 9l3 3 247 247 3 3c3 1 6 2 9 2s6-1 9-2l3-3 247-247 3-3c1-3 2-6 2-9V53c0-10-2-18-7-27-5-8-11-14-19-19-9-5-17-7-27-7H264c-3 0-6 1-9 2l-3 3L5 252l-3 3zm41 9L271 35h204c3 0 6 1 9 3 3 1 5 3 6 6 2 3 3 6 3 9h35-35v204L264 485 43 264zm318-90c-3-2-5-4-7-7-1-3-2-5-2-9 0-3 1-6 2-8 2-3 4-5 7-7 3-1 5-2 9-2 3 0 6 1 8 2 3 2 5 4 7 7 1 2 2 5 2 8 0 4-1 6-2 9-2 3-4 5-7 7-2 1-5 2-8 2-4 0-6-1-9-2zm-37 11c5 8 11 14 19 19 9 5 17 7 27 7 9 0 18-2 26-7s14-11 19-19c5-9 7-17 7-27 0-9-2-18-7-26s-11-14-19-19-17-7-26-7c-10 0-18 2-27 7-8 5-14 11-19 19s-7 17-7 26c0 10 2 18 7 27z"/></g></g></g></g></g></svg>',
};
